### ISSUE TITLE
Encountered A build question 

### ISSUE THREAD

**Issue by willhunger** [acyortjs/acyort#30]
build以后出现了如下错误：
Data from cache... 
Getting data from GitHub (willhunger/willhunger.github.io)  ... 1
✖ No contents

然后acrort server 后出现的页面信息是404

**Comment by LoeiFy** [comment]
同时出现这两段文字？
```
Data from cache...
Getting data from GitHub (willhunger/willhunger.github.io) ... 1
```
按道理不应该同时出现这两句的，这边要测试一下

**Comment by willhunger** [comment]
现在好了，是我repo的问题。
不过，在自动构建的时候出现了一个问题：
The command "git clone git@github.com:willhunger/BlogBuild.git public" failed and exited with 128 during .
Your build has been stopped.
你说那个用于自动构建的repo是需要设置一个public的文件夹吗？还是什么意思？
可是我也没有从你的那个Demo的repo里面看到这么一个文件夹呀。

**Comment by willhunger** [comment]
> 
> $ git clone git@github.com:willhunger/BlogBuild.git public
> 
> Cloning into 'public'...
> 
> Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
> 
> Permission denied (publickey).
> 
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> 
> and the repository exists.
> 

这是错误的上面部分，是我的token出现问题了吗？不解

**Comment by LoeiFy** [comment]
你不能用 ssh 方式来 clone 项目，因为需要 sshkey 问题，需要用 https 方式

参照这个教程：https://github.com/acyortjs/acyortjs.github.io/issues/13

**Comment by willhunger** [comment]
多谢你，还有一问题

> 0.03s$ git push https://${GH_TOKEN}@github.com/willhunger/BlogBuild.git gh-pages:gh-pages
> 
> error: src refspec gh-pages does not match any.
> 
> error: failed to push some refs to 'https://[secure]@github.com/willhunger/BlogBuild.git'

这应该是我repo的问题吗？

**Comment by willhunger** [comment]
貌似是repo的分支不被识别，请问如何解决？

**Comment by LoeiFy** [comment]
```yml
before_script:
  - git clone https://github.com/willhunger/Blog.git public
  - cd public
```

这里的配置 repo 错了，应该是

```yml
before_script:
  - git clone https://github.com/willhunger/BlogBuild.git public
  - cd public
```

**Comment by willhunger** [comment]
我全部更改了一遍终于好了，谢谢大佬一直耐心为我解答。
不过路由混乱改如何处理呢？

1. 

[这里是我的博客https://willhunger.github.io/BlogBuild/](https://willhunger.github.io/BlogBuild/)
但是我在首页点logo的时候指向的是https://willhunger.github.io/BlogBuild/BlogBuild

2. 

如果我需要默认指向https://willhunger.github.io/ 的话，除了更改repo的名字为*.gitgub.io以外还有什么方法吗？

**Comment by LoeiFy** [comment]
你需要用 `xxxname.github.io` 作为项目名，才可以使用 github.io 的二级域名。或者你可以绑定 cname，具体相关说明你可以网站找一些 GitHub pages 个人网站相关教程

**Comment by willhunger** [comment]
还是不能成功，生成的[index.html](https://github.com/willhunger/BlogBuild/blob/gh-pages/index.html)依旧是/BlogBuild/BlogBuild。
我有点不解了

**Comment by willhunger** [comment]
https://willhunger.github.io/BlogBuild/
您现在去看一下吧，感觉问题是出在生成的logo处

**Comment by LoeiFy** [comment]
想起来了，是模板引用变量错了，等我修改一下

**Comment by willhunger** [comment]
修改好了在issues中回复一下。
对了，在配置文件中看到了Disqus这个配置，
如果要加入这个功能，要如何配置呢？

**Comment by LoeiFy** [comment]
链接已经修复过来了，你重新触发 build 就可以了

disqus 可以在 `config.yml` 里面设置，开启 disqus 字段 `disqus: 你的 disqus 用户名`，然后你的页面就会有评论了（需要主题做支持，`donob` 主题已经支持了）

**Comment by willhunger** [comment]
我有一个大胆的想法，能不能有让方法让acyort做到与Hexo主题的兼容呢？

**Comment by LoeiFy** [comment]
其实有相通的地方的，只是数据格式有点不一样，不过还在添加新功能，暂时不考虑这个主题的

**Comment by willhunger** [comment]
可以的，加油哦，会一直关注你的。

**Comment by willhunger** [comment]
webhook是需要独立运行在vps上的吗？

**Comment by LoeiFy** [comment]
是的，因为 travis cl 并没有可以用 issue 触发构建的功能
