### ISSUE TITLE
Time and disqus questions

### ISSUE THREAD

**Issue by willhunger** [acyortjs/acyort#31]
- 文章的时间问题  
    就是当一个issue已经被build以后，下一次更新issue以后再build，文章的时间显示为第二次生成的时间。  
我的建议是在配置文件中提供两种时间供选择，选择是第一次发表时间还是更新时间为时间标准。

- disqus反向代理  
    [https://github.com/ciqulover/disqus-proxy](https://github.com/ciqulover/disqus-proxy)

**Comment by LoeiFy** [comment]
第一个问题是可以加一个配置，第二个关于 disqus 的，这个让主题模板自己去做适应吧，这个工具不提供支持
