### ISSUE TITLE
Support to change the post date

### ISSUE THREAD

**Issue by Huangsir** [acyortjs/acyort#36]
All the post time will be the same after migrate old blog to `issues blog`.   
hope to overwrite the post time by add something like 
```
// create_at: YYYY-mm-DD HH:MM:SS
```
on the top of the post.

**Comment by LoeiFy** [comment]
AcyOrt supports 'custom scripts(plugins)' now, and i am making scripts for 'hexo' and 'jekyll'. please wait for a few days

**Comment by LoeiFy** [comment]
you can change theme templates for custom times

**Comment by LoeiFy** [comment]
@Huangsir the script example:
https://github.com/acyortjs/acyort/blob/master/assets/scripts/hexo.js
