### ISSUE TITLE
toc有些问题

### ISSUE THREAD

**Issue by flcker** [acyortjs/acyort#37]
我在搭建博客的时候发现一个问题，toc目录和正文会重叠，在chrome里不会出现，在Microsoft Edge里会出现。

截图：
![image](https://user-images.githubusercontent.com/7287246/33236829-b3a4f06a-d29a-11e7-9c07-b47f5467c4ab.png)

**Comment by LoeiFy** [comment]
这个是 css 兼容问题，因为这个默认模板用于展示所有功能，并没有花太多时间在样式方面，所以有兼容性问题
