### ISSUE TITLE
请问如何启用评论功能？如何解决gh-pages分支显示“NO TESTS”？

### ISSUE THREAD

**Issue by Astraeux** [acyortjs/acyort#41]
1. 请问如何启用评论功能？[这篇文章](https://github.com/LoeiFy/Recordum/issues/19)里说评论功能已实现，但在文档和配置中未找到评论启用开关。

2. circleci部署好后master分支显示编译成功，gh-pages分支显示“NO TESTS”，如何解决？
![image](https://user-images.githubusercontent.com/3686767/37501287-9fff1e18-2908-11e8-9974-da3942e02042.png)

**Comment by LoeiFy** [comment]
1. 评论功能需要主题支持，现在内置主题已经把这个去掉了，之前用的是 disqus，你可以在模板加上

https://github.com/acyortjs/acyort/blob/master/assets/themes/ccc45/layout/post.html#L41-L42

2. gh-pages 分支是用于存放静态文件的，没有 ci 配置文件，所以更新触发构建是会显示 no tests 的，正常情况

**Comment by Astraeux** [comment]
可否实现Mirror那样，读取文章issue里的评论呢？

**Comment by LoeiFy** [comment]
获取 issue 评论可以使用插件方式通过 api 方式获取，具体可以参考 api 插件做法

**Comment by Astraeux** [comment]
请问有计划将该功能作为官方示范插件吗？

**Comment by LoeiFy** [comment]
觉得这个功能还不错，是考虑弄一个插件的
