### ISSUE TITLE
timezone设置不生效

### ISSUE THREAD

**Issue by wuzehv** [acyortjs/acyort#46]
作者你好：
今天偶然发现博客的时区设置好像不生效，操作如下：
```
# 在config.yml中，把时区从上海，改到纽约
timezone: America/New_York
```

看自动构建的日志的最后一步：
```
git commit -m "Updated by CircleCI - `TZ='Asia/Shanghai' date`"

On branch gh-pages
Your branch is up-to-date with 'origin/gh-pages'.
nothing to commit, working directory clean
Exited with code 1
```

这是说明文件都没有被修改，所以猜测可能是时区设置未生效。

还有就是生成的博客时间感觉像是UTC时间，跟当前时间差了大概八小时左右，例如下面这篇文章，是今天十点左右更新的。

https://wuzehui.top/posts/352966584.html

博客项目地址：
https://github.com/wuzehv/blog2

麻烦帮忙看看， 谢谢 :)

**Comment by LoeiFy** [comment]
我这边测试下，还有你如果是需要修改主题，可以自定义主题的，像这个：https://github.com/acyortjs/theme-donob
