### ISSUE TITLE
circleci 构建错误

### ISSUE THREAD

**Issue by fydy** [acyortjs/acyort#51]
Exit code: 1
#!/bin/bash -eo pipefail
cp config.bak.yml config.yml
cp: cannot stat 'config.bak.yml': No such file or directory
Exited with code 1

**Comment by LoeiFy** [comment]
把 circleci 配置文件中的 `npm i acyort -g` 改成 `npm i acyort@2.3 -g`

**Comment by fydy** [comment]
@LoeiFy 又出现这个问题
![image](https://user-images.githubusercontent.com/39726855/49556265-f98eb280-f93d-11e8-87c0-fd02fc17f48f.png)

**Comment by LoeiFy** [comment]
你照着这个例子 [项目](https://github.com/LoeiFy/Recordum) 目录来，如果不大知道流程的话。

这个问题是你把 scripts 目录加到 master 分支了，在 checkout 到 gh-pages 分支时候，scripts 目录已经没有了

**Comment by fydy** [comment]
@LoeiFy 按照项目构建成功了，1）如何访问，我看gh-pages有更新，但是访问域名提示错误。2）每次master分支构建完成后，又自动构建gh-pages 分支，gh-pages提示错误。谢谢！
