### ISSUE TITLE
访问错误

### ISSUE THREAD

**Issue by fydy** [acyortjs/acyort#52]
按照项目构建成功了，1）如何访问，我看gh-pages有更新，但是访问提示错误。2）每次master分支构建完成后，又自动构建gh-pages 分支，gh-pages提示错误。谢谢

**Comment by LoeiFy** [comment]
1. github pages cname 问题，这个你自己排查
2. 这个错误不用理会，不影响

**Comment by fydy** [comment]
@LoeiFy ok，successfully。thank you.
